id: projet12_consumers_to_slack
namespace: openclassroom.p12

labels:
  strava: 004_Consumer_redpanda_to_slack



triggers:
  - id: redpanda_trigger
    type: io.kestra.plugin.kafka.Trigger
    topic: Strava_json
    properties:
      bootstrap.servers: redpanda:9092
    groupId: strava-consumer-group-to-slack 
    valueDeserializer: JSON
    keyDeserializer: STRING
    interval: PT20S
    maxRecords: 1


tasks:

  - id: json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ trigger.uri }}"


  - id: transform_for_slack
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python-strava-pandas:1.0
    pythonVersion: "3.12"
    inputFiles:
      input.json: "{{ outputs.json.uri }}"
      script.py: file:///app/storage/scripts/consumer_to_slack.py
    outputFiles:
      - output.txt 
    commands:
      - python script.py

  - id: send_to_slack
    type: io.kestra.plugin.slack.app.chats.Post
    token: "{{ secret('TOKEN_ID') }}"
    channel: "{{ secret('CHANNEL_ID') }}"
    messageText: "{{ read(outputs.transform_for_slack.outputFiles['output.txt']) }}"


