id: projet12_consumers_to_BI
namespace: openclassroom.p12

labels:
  strava: 005_Consumer_redpanda_to_BI_spark





triggers:
  - id: redpanda_trigger
    type: io.kestra.plugin.kafka.Trigger
    topic: Strava_json
    properties:
      bootstrap.servers: redpanda:9092
    groupId: strava-consumer-group-to-BI
    valueDeserializer: JSON
    keyDeserializer: STRING
    interval: PT20S
    maxRecords: 1



tasks:
  - id: json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ trigger.uri }}"

  - id: normalize
    type: io.kestra.plugin.scripts.python.Script
    outputFiles:
      - data.json
    script: |
      import json

      records = []
      with open("{{ outputs.json.uri }}", "r") as f:
          for line in f:
              line = line.strip()
              if not line:
                  continue
              record = json.loads(line)
              value = record["value"]
              if isinstance(value, str):
                  value = json.loads(value)
              records.append(value)

      with open("data.json", "w") as f:
          json.dump(records, f)

  - id: send_each_record
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ read(outputs.normalize.outputFiles['data.json']) }}"
    tasks:
      - id: Insert_in_fact_table
        type: io.kestra.plugin.jdbc.postgresql.Query
        url: jdbc:postgresql://postgres:5432/{{ secret('POSTGRES_DB') }}
        username: "{{ secret('POSTGRES_USER') }}"
        password: "{{ secret('POSTGRES_PASSWORD') }}"
        sql: |
          INSERT INTO dwh.fact_sport_activity (
                  id,
                  id_salarie,
                  id_sport,
                  date_id,
                  duration_minutes,
                  distance_m
              )
              SELECT
                  '{{ json(taskrun.value).id }}'::uuid,
                  {{ json(taskrun.value).id_salarie }},
                  ds.id_sport,
                  CAST('{{ json(taskrun.value).start_time }}' AS timestamp)::date,
                  {{ json(taskrun.value).duration_minutes }},
                  {{ json(taskrun.value).distance_m ?? 'NULL' }}
              FROM dwh.dim_sport ds
              WHERE ds.type_sport = '{{ json(taskrun.value).type_sport }}'
              ON CONFLICT (id) DO NOTHING;