services:

#####################
# Kestra
######################

  postgres_kestra:
    image: postgres:18
    container_name: postgres_kestra
    restart: always
    volumes:
      - postgres_kestra-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB_kestra}
      POSTGRES_USER: ${POSTGRES_USER_kestra}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_kestra}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB_kestra} -U $${POSTGRES_USER_kestra}"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - kestra-net



  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    restart: always
    user: "root"
    command: server standalone
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd

    env_file:
      - .env_encoded

    environment:
      POSTGRES_DB_kestra: ${POSTGRES_DB_kestra}
      POSTGRES_USER_kestra: ${POSTGRES_USER_kestra}
      POSTGRES_PASSWORD_kestra: ${POSTGRES_PASSWORD_kestra}
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres_kestra:5432/${POSTGRES_DB_kestra}
            driverClassName: org.postgresql.Driver
            username: ${POSTGRES_USER_kestra}
            password: ${POSTGRES_PASSWORD_kestra}     
        kestra:
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          local-files:
            enabled: true
            allowed-paths:
              - "/app/storage"
              - "/app/storage/**" 
          url: http://localhost:8080/
          
    depends_on:
      redpanda:
        condition: service_started
      postgres:
        condition: service_started
      postgres_kestra:
        condition: service_healthy      
    networks:
      - kestra-net


#####################
# Redpanda
######################
  redpanda:
    image: redpandadata/redpanda:v26.1.6
    container_name: redpanda
    restart: always
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092 
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092 # 
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kestra-net


  redpanda_console:
    image: redpandadata/console:v3.7.2
    container_name: redpanda_console
    restart: always    
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    networks:
      - kestra-net



#####################
# BDD:  PostgreSQL
######################
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres-init:/docker-entrypoint-initdb.d
    command:
      - postgres
      - -c
      - wal_level=logical
    networks:
      - kestra-net

  #####################
  # BI :  Metabase
  ######################
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase.db   
    depends_on:
      - postgres
    networks:
      - kestra-net



  #####################
  #Monitopring: Prometheus grafana
  ######################

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'    
    networks:
      - kestra-net


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"  
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - kestra-net


volumes:
  redpanda_data:
  postgres_data:
  prometheus_data:
  grafana_data:
  postgres_kestra-data:
  metabase-data:


networks:
  kestra-net:
    driver: bridge
    name: kestra-net
    
    
