id: projet12_trigger_postgresql_to_producer_strava_multi
namespace: openclassroom.p12

labels:
  strava: 003_Capture_debezium_to_producer_redpanda

triggers:
  - id: capture_data
    type: io.kestra.plugin.debezium.postgres.Trigger
    hostname: postgres
    port: 5432
    username: "{{ secret('POSTGRES_USER') }}"
    password: "{{ secret('POSTGRES_PASSWORD') }}"
    database: "{{ secret('POSTGRES_DB') }}"
    pluginName: PGOUTPUT
    snapshotMode: INITIAL
    includedTables: strava.sport
    interval: PT1S 

tasks:

  - id: json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ trigger.uris['strava.sport'] }}"

  - id: python_nettoyage_capture
    type: io.kestra.plugin.scripts.python.Script
    outputFiles:
      - messages.json
    script: |
      import json

      champs = ['id', 'id_salarie', 'nom', 'prenom', 'type_sport', 'start_time', 'duration_minutes', 'distance_m']

      records_filtres = []

      with open("{{ outputs.json.uri }}", "r") as fopen:
          for line in fopen:
              line = line.strip()
              if not line:
                  continue
              record = json.loads(line)
              record_filtre = {k: record[k] for k in champs if k in record}
              records_filtres.append(record_filtre)

      with open("messages.json", "w") as f:
          json.dump(records_filtres, f, ensure_ascii=False)

  - id: send_each_record
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ json(read(outputs.python_nettoyage_capture.outputFiles['messages.json'])) }}"
    tasks:
      - id: redpanda_producer
        type: io.kestra.plugin.kafka.Produce
        properties:
          bootstrap.servers: redpanda:9092
        topic: Strava_json
        from:
          key: "{{ execution.id }}_{{ taskrun.value | jq('.id') | first }}"
          value: "{{ taskrun.value }}"
        keySerializer: STRING
        valueSerializer: JSON
