id: projet12_strava2
namespace: openclassroom.p12

triggers:
  - id: capture_data
    type: io.kestra.plugin.debezium.postgres.Trigger
    hostname: postgres
    port: 5432
    username: "{{ secret('POSTGRES_USER') }}"
    password: "{{ secret('POSTGRES_PASSWORD') }}"
    database: "{{ secret('POSTGRES_DB') }}"
    pluginName: PGOUTPUT
    snapshotMode: INITIAL

tasks:
 
  - id: prepare_messages
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    containerImage: python:3.12
    inputFiles:
      input.json: "{{ trigger.uris['strava.sport'] ?? '' }}"
    outputFiles:
      - messages.json
    script: |
      import os
      import re
      import json

      if os.path.exists("input.json") and os.path.getsize("input.json") > 0:
          with open("input.json", "r") as f:
              raw_content = f.read().strip()
          
          data = {}
          champs = ['id', 'id_salarie', 'nom', 'prenom', 'type_sport', 'duration_minutes']
          
          for champ in champs:
              match = re.search(rf'\b{champ}\s*:\s*([^,}}]+)', raw_content, re.IGNORECASE)
              if match:
                  val = match.group(1).strip().strip('"').strip("'")
                  if champ in ['id_salarie', 'duration_minutes']:
                      try: val = int(val)
                      except: val = 0
                  data[champ] = val
          
          with open("messages.json", "w", encoding="utf-8") as f_out:
              f_out.write(json.dumps(data, ensure_ascii=False) + "\n")
      else:
          with open("messages.json", "w") as f_out:
              f_out.write("{}\n")



  - id: redpanda_producer
    type: io.kestra.plugin.kafka.Produce
    properties:
      bootstrap.servers: redpanda:9092
    topic: Strava_json
    from:
      key: "{{ execution.id }}"
      value: "{{ json(read(outputs.prepare_messages.outputFiles['messages.json'])) }}"
    keySerializer: STRING
    valueSerializer: JSON

  - id: Consumers
    type: io.kestra.plugin.core.flow.Parallel
    tasks:

      - id: Consumers_to_slack
        type: io.kestra.plugin.core.flow.Sequential
        tasks:

          - id: Redpanda_consumer_to_slack
            type: io.kestra.plugin.kafka.Consume
            topic: Strava_json
            properties:
              bootstrap.servers: redpanda:9092
              group.id: strava-consumer-group-to-slack          
              auto.offset.reset: latest                
            pollDuration: PT5S
            maxRecords: 3
            keyDeserializer: STRING
            valueDeserializer: JSON


          - id: transform_for_slack
            type: io.kestra.plugin.scripts.python.Commands
            taskRunner:
              type: io.kestra.plugin.scripts.runner.docker.Docker
            containerImage: python-strava-pandas:1.0
            pythonVersion: "3.12"
            inputFiles:
              input.json: "{{ outputs.Redpanda_consumer_to_slack.uri }}"
              script.py: file:///app/storage/scripts/consumer_to_slack.py
            outputFiles:
              - output.txt 
            commands:
              - python script.py

          - id: send_to_slack
            type: io.kestra.plugin.slack.app.chats.Post
            token: "{{ secret('TOKEN_ID') }}"
            channel: "{{ secret('CHANNEL_ID') }}"
            messageText: "{{ read(outputs.transform_for_slack.outputFiles['output.txt']) }}"


